### ISSUE TITLE
Ontario California

### ISSUE THREAD

**Issue by TheAngryAmish** [david733/baseballmap#1]
![ontario california2](https://user-images.githubusercontent.com/5758761/28499804-74e2695a-6f8c-11e7-8ccc-b92feceef5a0.png)
![ontario california](https://user-images.githubusercontent.com/5758761/28499798-4ed4e7c4-6f8c-11e7-8fa5-c056a1607891.png) Their seems to be a bug putting the blue jays in So Cal instead of up north. Probably has to do with Ontario Ca, being a real place and not just the one in canada.

**Comment by david733** [comment]
Thanks for the catch! You're right, the geocoding interpreted the city as Ontario, CA instead of Canada. The table has been manually fixed.
